-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("BufWritePost", {
--     pattern = "*.tex",
--     callback = function()
--         -- local current_file = vim.fn.expand("%")
--         -- vim.notify(current_file, vim.log.levels.INFO)
--         require("file_history").backup()
--     end,
--     desc = "Backup files on save",
-- })
