#!/bin/bash

# Set monitors using xrandr
$HOME/.screenlayout/dualmonitor.sh

# OpenRGB
openrgb -p off

# Restart hotkeys server
pgrep -x sxhkd > /dev/null || sxhkd &

# Compositor
picom -b --experimental-backends &

# For apps like Intellij
wmname LG3D

# Restart programs as necessary
pkill latte-dock
latte-dock
pkill plasmashell
kstart5 plasmashell &
$HOME/.config/polybar/launch.sh &

blue light
if [ "$(pgrep redshift)" == "" ]
then
	$HOME/Scripts/toggle-bluelight.sh
fi

# Swallowing
pgrep bspswallow || bspswallow &

# Aesthetic stuff
bspc config border_width         0
bspc config focused_border_color \#FFFFFF
bspc config split_ratio          0.5
bspc config window_gap           20

# Workspaces
# For second monitor (if connected)
if [ $(xrandr | grep -c ' connected') -gt 1 ]
then
    bspc config -m $(cat $HOME/vars/monitorscreen) window_gap 32
    bspc monitor $(cat $HOME/vars/laptopscreen) -d 1 2 3 4 5 
    bspc monitor $(cat $HOME/vars/monitorscreen) -d 6 7 8 9 10
else
    bspc monitor $(cat $HOME/vars/laptopscreen) -d 1 2 3 4 5 6
fi


#xdo lower -n latte-dock
#xdo lower -n plasmashell

# Rules
bspc rule -a Pavucontrol state=floating rectangle=1000x500+800+52
bspc rule -a obs state=floating
bspc rule -a Zathura state=tiled
