#!/bin/sh

# Set monitors using xrandr if 2 monitors connected
if [ $(xrandr | grep -c ' connected') -gt 1 ]
then
$HOME/.screenlayout/dualmonitor.sh
fi

# Restart hotkeys server
pgrep -x sxhkd > /dev/null || sxhkd &

# Compositor
/usr/bin/picom -b --experimental-backends &

# For apps that are written in Java Swing
wmname LG3D

# Blue light filter
blue light
if [ "$(pgrep redshift)" == "" ]
then
	$HOME/Scripts/toggle-bluelight.sh
fi

# Swallowing
pgrep bspswallow || bspswallow &

# Aesthetic stuff
bspc config border_width         0
bspc config focused_border_color \#FFFFFF
bspc config split_ratio          0.5
bspc config window_gap           20

# Workspaces

# Dual monitor
if [ $(xrandr | grep -c ' connected') -gt 1 ]
then
    bspc config -m $(cat $HOME/vars/monitorscreen) window_gap 32
    bspc monitor $(cat $HOME/vars/laptopscreen) -d 1 2 3 4 5 
    bspc monitor $(cat $HOME/vars/monitorscreen) -d 6 7 8 9 10
    $HOME/.config/polybar/launch-dual.sh &
# Single monitor
else
    bspc monitor -d 1 2 3 4 5 6
    $HOME/.config/polybar/launch-single.sh &

fi

# Make latte dock visible
xdo lower -n polybar
xdo lower -n plasmashell

# Rules
bspc rule -a obs state=floating
bspc rule -a Zathura state=tiled
